// <auto-generated />
namespace Kurumsal_Web11.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SyncWithDatabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SyncWithDatabase));
        
        string IMigrationMetadata.Id
        {
            get { return "202501132144506_SyncWithDatabase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
